### ISSUE TITLE
Error when trying to configure kernel previous to build

### ISSUE THREAD

**Issue by timoteogb** [SundanceMultiprocessorTechnology/FM191_FW#1]
```
timin@timin:/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel$ petalinux-config -c kernel
[INFO] generating Kconfig for project
                                                                                                                                                                                       
[INFO] sourcing bitbake
[INFO] generating plnxtool conf
[INFO] generating meta-plnx-generated layer
/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/misc/plnx-generated /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel
/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel
[INFO] generating machine configuration
[INFO] configuring: kernel
[INFO] generating kernel configuration files
[INFO] bitbake virtual/kernel -c menuconfig
WARNING: Host distribution "Ubuntu-18.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |###################################################################################################################################################| Time: 0:00:01
Loaded 3257 entries from dependency cache.
Parsing recipes: 100% |#################################################################################################################################################| Time: 0:00:03
Parsing of 2466 .bb files complete (2434 cached, 32 parsed). 3259 targets, 226 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
tar: ./x86_64-linux/usr/lib/libstdc++.so.6: Cannot create symlink to 'libstdc++.so.6.0.22': Operation not permitted
tar: ./x86_64-linux/lib/libnss_dns.so.2: Cannot create symlink to 'libnss_dns-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libutil.so.1: Cannot create symlink to 'libutil-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libanl.so.1: Cannot create symlink to 'libanl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnss_compat.so.2: Cannot create symlink to 'libnss_compat-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/librt.so.1: Cannot create symlink to 'librt-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libBrokenLocale.so.1: Cannot create symlink to 'libBrokenLocale-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libdl.so.2: Cannot create symlink to 'libdl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libmvec.so.1: Cannot create symlink to 'libmvec-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/ld-linux-x86-64.so.2: Cannot create symlink to 'ld-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libm.so.6: Cannot create symlink to 'libm-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnss_files.so.2: Cannot create symlink to 'libnss_files-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libcrypt.so.1: Cannot create symlink to 'libcrypt-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libresolv.so.2: Cannot create symlink to 'libresolv-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libc.so.6: Cannot create symlink to 'libc-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnsl.so.1: Cannot create symlink to 'libnsl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libpthread.so.0: Cannot create symlink to 'libpthread-2.23.so': Operation not permitted
tar: ./x86_64-linux/etc/ld.so.cache: Cannot create symlink to '/etc/ld.so.cache': Operation not permitted
tar: Exiting with failure status due to previous errors
/bin/sh: 1: /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/relocate_sdk.py: Permission denied
WARNING: Disabling uninative as unable to install uninative tarball: Command 'mkdir -p /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative; cd /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative; tar -xjf /home/Petalinux/components/yocto/source/arm/downloads/uninative/26c8078f6f58249582bb9edecec6d2f5617e06422c4094528ba43cb13831bdcf/x86_64-nativesdk-libc.tar.bz2; /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/relocate_sdk.py /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/x86_64-linux /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/x86_64-linux//usr/bin/patchelf-uninative /media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/sysroots-uninative/x86_64-linux/lib/libc*.so' returned non-zero exit status 126
WARNING: To build your own uninative loader, please bitbake uninative-tarball and set UNINATIVE_TARBALL appropriately.
Initialising tasks: 100% |##############################################################################################################################################| Time: 0:00:00
NOTE: Executing RunQueue Tasks
ERROR: linux-xlnx-4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0 do_clean: Execution of event handler 'sstate_eventhandler' failed
Traceback (most recent call last):
  File "/home/Petalinux/components/yocto/source/arm/layers/core/meta/classes/sstate.bbclass", line 991, in sstate_eventhandler(e=<bb.build.TaskSucceeded object at 0x7f5ebab2a630>):
             sstatepkg = d.getVar('SSTATE_PKG', True)
    >        bb.siggen.dump_this_task(sstatepkg + '_' + taskname + ".tgz" ".siginfo", d)
     }
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 351, in dump_this_task(outfile='/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo', d=<bb.data_smart.DataSmart object at 0x7f5ec212a908>):
         referencestamp = bb.build.stamp_internal(task, d, None, True)
    >    bb.parse.siggen.dump_sigtask(fn, task, outfile, "customfile:" + referencestamp)
     
  File "/home/Petalinux/components/yocto/source/arm/layers/core/meta/lib/oe/sstatesig.py", line 184, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/Petalinux/components/yocto/source/arm/layers/meta-xilinx/recipes-kernel/linux/linux-xlnx_4.9.bb', task='do_clean', stampbase='/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo', runtime='customfile:/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/stamps/plnx_arm-xilinx-linux-gnueabi/linux-xlnx/4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0'):
                 return
    >        super(bb.siggen.SignatureGeneratorBasicHash, self).dump_sigtask(fn, task, stampbase, runtime)
     
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 307, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/Petalinux/components/yocto/source/arm/layers/meta-xilinx/recipes-kernel/linux/linux-xlnx_4.9.bb', task='do_clean', stampbase='/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo', runtime='customfile:/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/stamps/plnx_arm-xilinx-linux-gnueabi/linux-xlnx/4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0'):
                     pass
    >            raise err
     
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 301, in SignatureGeneratorOEBasicHash.dump_sigtask(fn='/home/Petalinux/components/yocto/source/arm/layers/meta-xilinx/recipes-kernel/linux/linux-xlnx_4.9.bb', task='do_clean', stampbase='/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo', runtime='customfile:/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/tmp/stamps/plnx_arm-xilinx-linux-gnueabi/linux-xlnx/4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0'):
                 os.chmod(tmpfile, 0o664)
    >            os.rename(tmpfile, sigfile)
             except (OSError, IOError) as err:
OSError: [Errno 22] Invalid argument: '/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sigtask.d2uhv4el' -> '/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo'

ERROR: linux-xlnx-4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0 do_clean: Build of do_clean failed
ERROR: linux-xlnx-4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd-r0 do_clean: Traceback (most recent call last):
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/build.py", line 643, in exec_task
    return _exec_task(fn, task, d, quieterr)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/build.py", line 617, in _exec_task
    event.fire(TaskSucceeded(task, logfn, localdata), localdata)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/event.py", line 201, in fire
    fire_class_handlers(event, d)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/event.py", line 124, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/event.py", line 96, in execute_handler
    ret = handler(event)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/meta/classes/sstate.bbclass", line 991, in sstate_eventhandler
    bb.siggen.dump_this_task(sstatepkg + '_' + taskname + ".tgz" ".siginfo", d)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 351, in dump_this_task
    bb.parse.siggen.dump_sigtask(fn, task, outfile, "customfile:" + referencestamp)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/meta/lib/oe/sstatesig.py", line 184, in dump_sigtask
    super(bb.siggen.SignatureGeneratorBasicHash, self).dump_sigtask(fn, task, stampbase, runtime)
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 307, in dump_sigtask
    raise err
  File "/home/Petalinux/components/yocto/source/arm/layers/core/bitbake/lib/bb/siggen.py", line 301, in dump_sigtask
    os.rename(tmpfile, sigfile)
OSError: [Errno 22] Invalid argument: '/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sigtask.d2uhv4el' -> '/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sstate:linux-xlnx:plnx_arm-xilinx-linux-gnueabi:4.9-xilinx-v2017.4+gitAUTOINC+b450e900fd:r0:plnx_arm:3:aaf9d19e99dd97c7645b37741cd0bce7_clean.tgz.siginfo'

ERROR: Task (/home/Petalinux/components/yocto/source/arm/layers/meta-xilinx/recipes-kernel/linux/linux-xlnx_4.9.bb:do_clean) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/Petalinux/components/yocto/source/arm/layers/meta-xilinx/recipes-kernel/linux/linux-xlnx_4.9.bb:do_clean
Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
ERROR: bitbake failed to cleansstate kernel
ERROR: Failed to config kernel.
webtalk failed:PetaLinux statistics:extra lines detected:notsent_nofile!
webtalk failed:Failed to get PetaLinux usage statistics!
timin@timin:/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel$ 

```

**Comment by pedrombmachado** [comment]
@timoteogb 
Can you please check if this file exists?
/media/timin/Transcend/Petalinux_projects/Kernel_FM191/FM191_kernel/build/sstate-cache/aa/sigtask.d2uhv4el
If so what are the file permissions?
```
$ ls -la
```
This file should be 644 [os.chmod(tmpfile, 0o664)]

**Comment by timoteogb** [comment]
"aa" is empty

**Comment by pedrombmachado** [comment]
@timoteogb ,
  Found the reason why:
```
tar: ./x86_64-linux/usr/lib/libstdc++.so.6: Cannot create symlink to 'libstdc++.so.6.0.22': Operation not permitted
tar: ./x86_64-linux/lib/libnss_dns.so.2: Cannot create symlink to 'libnss_dns-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libutil.so.1: Cannot create symlink to 'libutil-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libanl.so.1: Cannot create symlink to 'libanl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnss_compat.so.2: Cannot create symlink to 'libnss_compat-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/librt.so.1: Cannot create symlink to 'librt-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libBrokenLocale.so.1: Cannot create symlink to 'libBrokenLocale-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libdl.so.2: Cannot create symlink to 'libdl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libmvec.so.1: Cannot create symlink to 'libmvec-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/ld-linux-x86-64.so.2: Cannot create symlink to 'ld-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libm.so.6: Cannot create symlink to 'libm-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnss_files.so.2: Cannot create symlink to 'libnss_files-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libcrypt.so.1: Cannot create symlink to 'libcrypt-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libresolv.so.2: Cannot create symlink to 'libresolv-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libc.so.6: Cannot create symlink to 'libc-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libnsl.so.1: Cannot create symlink to 'libnsl-2.23.so': Operation not permitted
tar: ./x86_64-linux/lib/libpthread.so.0: Cannot create symlink to 'libpthread-2.23.so': Operation not permitted
tar: ./x86_64-linux/etc/ld.so.cache: Cannot create symlink to '/etc/ld.so.cache': Operation not permitted
tar: Exiting with failure status due to previous errors
```
The symbolic links where not created. I guess that is because the script requires admin rights.
```
$ sudo <script name>
```

**Comment by pedrombmachado** [comment]
@timoteogb 
Try to mount the pen in : 
```
$ sudo mkdir -p /tmp/pen
$ sudo mount /dev/<pen> /tmp/pen
$ sudo chmod -R 0777 /tmp/pen
```
NOTE:
1) You need unmount the pen first
2) You may have to specify the file system using -t 

-t, --types vfstype
    The argument following the -t is used to indicate the filesystem type. The filesystem types which are currently supported include: adfs, affs, autofs, cifs, coda, coherent, cramfs, debugfs, devpts, efs, ext, ext2, ext3, ext4, hfs, hfsplus, hpfs, iso9660, jfs, minix, msdos, ncpfs, nfs, nfs4, ntfs, proc, qnx4, ramfs, reiserfs, romfs, squashfs, smbfs, sysv, tmpfs, ubifs, udf, ufs, umsdos, usbfs, vfat, xenix, xfs, xiafs.

**Comment by timoteogb** [comment]
This error doesn't happen when following the steps creating a folder anywhere in the int. SSD of my laptop. The cause of the error is me, trying to generate the kernel in a USB stick.
I'll try the suggestions above to solve it.

**Comment by timoteogb** [comment]
I've mounted the usb on /tmp/pen, giving it all the permissions (I typed the commands suggested above), and tried all again. Same error

**Comment by timoteogb** [comment]
The problem is solved formatting the USB stick to ext4 instead of FAT32.
